### ISSUE TITLE
IOS: Missing resource files

### ISSUE THREAD

**Issue by SanHoser** [CreativeSDK/phonegap-plugin-csdk-image-editor#1]
In the plugin.xml two resource files are defined, but are missing from the git repo.

```
    <resource-file src="src/ios/AdobeCreativeSDKFrameworks/AdobeCreativeSDKImage.framework/Versions/A/Resources/AdobeCreativeSDKImageResources.bundle" />
    <framework src="src/ios/AdobeCreativeSDKFrameworks/AdobeCreativeSDKImage.framework" custom="true" />
```

This will cause cordova platform add ios to fail after the plugin has been installed.

**Comment by macdonst** [comment]
@SanHoser yeah, I mention that you need to get the iOS SDK and extract it to the src/ios directory in the [README](https://github.com/CreativeSDK/phonegap-plugin-csdk-image-editor#prerequisites). Once cordova-ios supports cocoapods the plan is to include the SDK as a cocoapod so you can skip this step.

Make sense?

**Comment by vernondegoede** [comment]
Should the `src/ios` folder be in the root of the Cordova project?

**Comment by macdonst** [comment]
@vernondegoede nope, it is fine where it is. What matters is that the path in plugin.xml is correct.

**Comment by vernondegoede** [comment]
@macdonst Wow, you're fast. I'll try this now :)

**Comment by macdonst** [comment]
@vernondegoede well, we do need to clean some stuff up and a new release of Cordova will make the hooks directory go away which I'm happy for. Next week I'll be sitting down with the CSDK team to make more progress. Please let us know if you have any problems by raising issues.
