### ISSUE TITLE
Add a standard "Contributing" section to the readme

### ISSUE THREAD

**Issue by ashryanbeats** [CreativeSDK/phonegap-plugin-csdk-image-editor#12]

**Comment by macdonst** [comment]
@ashryanbeats we should skip adding CONTRIBUTING to README. Instead if we use GitHub's facilities we'd create a .github folder in the root of the repo. Inside that folder we can add stuff like CONTRIBUTING.md, ISSUE_TEMPLATE.md and PULL_REQUEST_TEMPLATE.md. You can see https://github.com/phonegap/phonegap-plugin-push/tree/master/.github for an example of what I've used. 

The benefits are described here: https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by ashryanbeats** [comment]
Oooh, this is great.
