### ISSUE TITLE
Did anybody got to use it with Ionic 2/TypeScript?

### ISSUE THREAD

**Issue by esl-douglas** [CreativeSDK/phonegap-plugin-csdk-image-editor#26]
### Expected Behaviour
Open the editor

### Actual Behaviour
Cannot find name 'CSDKImageEditor'

### Reproduce Scenario (including but not limited to)
Ionic 2 with creativeSDK plugin

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Web

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Web

#### PhoneGap CLI version and PhoneGap platform version
Ionic 2.1.18

#### Plugin version
1.0.0

**Comment by macdonst** [comment]
@esl-douglas only supported on Android and iOS not the web platform.

**Comment by tomsun** [comment]
@esl-douglas TypeScript assumes such a global variable is not defined probably. Try this inline: `const CSDKImageEditor = window['CSDKImageEditor'];`. Or write a typedef file...
