### ISSUE TITLE
Adobe shuts down legacy internal API, are this plugin's frameworks affected?

### ISSUE THREAD

**Issue by bryandh** [CreativeSDK/phonegap-plugin-csdk-image-editor#29]
I recently received an e-mail from Adobe saying:

> On July 24, 2017, we’ll be shutting down a legacy internal API that allows users to restore content pack downloads (effects, frames, overlays, stickers) in older versions of the Image Editor component.

> Developers using Image Editor versions 4.4.8 to 4.8.4 on Android, and 0.10.2096 to 0.15.2181.1 on iOS will not be impacted by this change. If you are using an earlier version of the Creative SDK Image Editor or the old Aviary SDK, we recommend upgrading to the latest version of the Creative SDK Image Editor. You can find the latest version of the Creative SDK here.

I am using plugin version 1.0.0.
The plugin automatically downloads the CreativeSDK framework for Android version com.adobe.creativesdk:image:4.6.3+, this version should keep on working after July 24, 2017 according to Adobe's e-mail.

The README states that for iOS, the framework has to manually be added => https://github.com/CreativeSDK/phonegap-plugin-csdk-image-editor#downloading-the-creative-sdk

The framework downloaded from that source is AdobeCreativeSDKImage.framework version 0.3.2181
This raised some concerns as this version seems to be older than the versions stated in the e-mail from Adobe.

Will this framework keep working after July 24, 2017?

**Comment by hanssens** [comment]
👍  +1 from me.

Today I received the same mail that @bryandh mentions. I'm also using the v1.0.0 plugin in a released app. I'm not really sure if this will have impact on the plugin and, if so, if there is an easy fix to make a PR for?

**Comment by hanssens** [comment]
Still wondering if this announcement will effect v1.0.0 of the plugin.
Perhaps @macdonst or @ashryanbeats have some insider info on this?

**Comment by macdonst** [comment]
@bryandh the plugin is setup to use the 4.6.3 or greater version of the CreativeSDK so as far as I know it will continue working.

**Comment by bryandh** [comment]
Is that also true for the iOS Creative SDK?
I've explained in the issue that this had to be manually installed and even the installation manual states its deprecated.

**Comment by macdonst** [comment]
The static framework downloaded from https://creativesdk.adobe.com/downloads.html# is v0.15.2181.1 which is in the range of SDK versions not affected.

**Comment by alien3d** [comment]
I like this  plugin and it work on ios 11 also but they said they not supporting it .
https://blog.creativesdk.com/2017/09/important-update-to-the-creative-sdk-end-of-support-for-the-image-editor-ui-color-ui-market-browser-and-labs-components/

As mention, they ask us to find altenative

1. I email photosdk .. but not respond by them

Suddenly today i check back... 
https://creativesdk.zendesk.com/hc/en-us/articles/202903359-Migrating-from-the-Aviary-SDK-to-the-Adobe-Creative-SDK
October 1 2017 ? Are adobe still support it till november or we need to find alternative..

Paying 10 dollar per month a service , and user like it .It very worth every penny

If they close it, hope adobe open their service and code so other will continue and don't have stall application
