### ISSUE TITLE
How to customize Image Editor options?

### ISSUE THREAD

**Issue by vernondegoede** [CreativeSDK/phonegap-plugin-csdk-image-editor#3]
Hi there,

I managed to install the Phonegap plugin for my iOS app. Looks like a great plugin so far! I couldn't find much documentation on customising this plugin so I'm asking it here... 

In the documentation\* I read that, in order to set crop options, I had to set 

```
// Disable the Custom and Original crop options, and do not allow the user to invert the settings.
[AdobeImageEditorCustomization setCropToolCustomEnabled:NO];
[AdobeImageEditorCustomization setCropToolInvertEnabled:NO];
[AdobeImageEditorCustomization setCropToolOriginalEnabled:NO];
```

But in which file am I supposed to do this? Should I add this directly to `/Users/vernon/Apps/Doka/platforms/ios/Doka/Plugins/phonegap-plugin-csdk-image-editor/AdobeCreativeSDKImage.framework/Headers/AdobeImageEditorCustomization.h` or is there a XML file which contains all these settings?

Thanks (again)!
- Documentation: https://creativesdk.adobe.com/docs/ios/#/articles/imageeditor/index.html

**Comment by vernondegoede** [comment]
@macdonst

**Comment by macdonst** [comment]
@vernondegoede yeah, sorry we still have to write the README. Here is a quick example:

```
ImageEditor.edit(function(data) {
        console.log('win: ' + data);
        var testElements = document.getElementsByClassName('test');
        var testDivs = Array.prototype.filter.call(testElements, function(testElement){
            testElement.style.backgroundImage='url(' + data + ')';
        });
      }, function(e) {
        console.log('error: ' + e);
      }, 'http://36.media.tumblr.com/c066cc2238103856c9ac506faa6f3bc2/tumblr_nmstmqtuo81tssmyno1_1280.jpg', {
          "outputType": ImageEditor.OutputType.JPEG,
          "tools": [ImageEditor.ToolType.STICKERS, ImageEditor.ToolType.BLUR],
          "quality": 25
      });
```

You pass in the array of tools you want to use. You can see the list of tools in www/index.js.

**Comment by vernondegoede** [comment]
Awesome! Thanks. Documentation still needs a lot of work, yeah :(
