### ISSUE TITLE
Check if `options.quality` is working as intended

### ISSUE THREAD

**Issue by ashryanbeats** [CreativeSDK/phonegap-plugin-csdk-image-editor#6]
JS: https://github.com/CreativeSDK/phonegap-plugin-csdk-image-editor/blob/dev/www/ImageEditor.js

Src: https://github.com/CreativeSDK/phonegap-plugin-csdk-image-editor/blob/dev/src/ios/CDVImageEditor.m

**Comment by macdonst** [comment]
@ashryanbeats when you get a chance, pull the latest update and re-test.

**Comment by ashryanbeats** [comment]
It's working! I'll note in the API guide that this option is for JPEGs only.
